# Generated by Django 6.0.7 on 2026-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Fid',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Sid',
            field=models.CharField(unique=True),
        ),
    ]
