# Generated by Django 6.0.7 on 2026-09-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_faculty_fid_alter_student_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semister',
            field=models.CharField(),
        ),
    ]
