# Generated by Django 6.0.7 on 2026-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='grade',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
